### ISSUE TITLE
Apple 2 disk 2 -- is it possible to connect?

### ISSUE THREAD

**Issue by gilmod714** [adafruit/Adafruit_Floppy#42]
is there a way to connect a disk II hardware (20 pin) directly and read disks ?! 

Thank you :)

**Comment by jepler** [comment]
Yes, you can use the greaseweazle-compatible firmware with a Disk ][ but you'll have to wire it for yourself and define the pinout in the `greaseweazle.ino` sketch. 

Here's how it's wired in the Adafruit Floppsy prototype, with the signal names being the Shugart/PC style floppy signal that it is shared with:
https://github.com/adafruit/Adafruit_Floppy/issues/25#issuecomment-2492118497 (plus index sensor modification hooked to on D26)

Here's how I wired it in a hand-wired custom featherwing: https://github.com/adafruit/Adafruit_Floppy/blob/f898470d334ccfb1a8775ddf16f1d01bc9dae8a3/examples/greaseweazle/greaseweazle.ino#L57

I recently verified that the code is working with the Floppsy prototype (imaged a floppy in my Disk ][ using greaseweazle on my linux PC)

There's also the shorter "apple2 test" which just prints some information about floppy flux on the serial connection: https://github.com/adafruit/Adafruit_Floppy/blob/main/examples/apple2_test/apple2_test.ino - I did not re-test this sketch since 2022, so it may not be working.

There isn't any code in Adafruit_Floppy for working with Apple GCR-coded floppy images.

Note that you need to supply the drive with 3 different voltages: +5, +12, and -12V.

Good luck with your project. Please understand that the issue tracker is not intended as a discussion forum. Thanks!

**Comment by gilmod714** [comment]
Thank you so much Jepler .. great information & guidance !! 

I will definitely be implementing this , the disk-II I have is brand new still boxed I got for free (NOS) .. trying to find a use for it on the PC ..
